//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirstEf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int ID { get; set; }
        public string urunAdi { get; set; }
        public Nullable<decimal> birimFiyat { get; set; }
        public Nullable<int> stokMiktar { get; set; }
    
        public virtual Kategori Kategori { get; set; }
    }
}
